oiat.saferinternetbot.web/Controllers/BotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace oiat.saferinternetbot.Web.Controllers
{
    public class BotController : Controller
    {
        // GET: Bot
        public ActionResult Index()
        {
            return View();
        }
    }
}

oiat.saferinternetbot.web/Controllers/CacheController.cs
using System.Web.Mvc;
using mbit.common.cache;

namespace oiat.saferinternetbot.web.Controllers
{
    public class CacheController : BaseController
    {
        private readonly ICacheService _cache;

        public CacheController(ICacheService cache)
        {
            _cache = cache;
        }

        [HttpGet]
        public ActionResult Invalidate(string redirectUrl)
        {
            _cache.InvalidateAll();
            PushSuccess("Cache leeren", "Cache wurde erfolgreich geleert");
            return Redirect(redirectUrl);
        }
    }
}

oiat.saferinternetbot.web/Controllers/IntentController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using oiat.saferinternetbot.Business.Interfaces;
using oiat.saferinternetbot.web.Models;

namespace oiat.saferinternetbot.web.Controllers
{
    [Authorize]
    public class IntentController : BaseController
    {
        private readonly IIntentService _intentService;
        private readonly IMapper _mapper;

        public IntentController(IIntentService intentService, IMapper mapper)
        {
            _intentService = intentService;
            _mapper = mapper;
        }

        public async Task<ActionResult> Index()
        {
            var items = await _intentService.GetAll();
            return View(_mapper.Map<IEnumerable<IntentViewModel>>(items));
        }
    }
}

oiat.saferinternetbot.web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using mbit.common.logging;
using oiat.saferinternetbot.Business.Identity;
using oiat.saferinternetbot.DataAccess.Entities;
using oiat.saferinternetbot.web.Models;

namespace oiat.saferinternetbot.web.Controllers
{
    [Authorize]
    public class UserController : BaseController
    {
        private static readonly IMcLogger _logger = McLogFactory.GetCurrentLogger();

        private readonly ApplicationUserManager _userManager;
        private readonly IMapper _mapper;

        public UserController(ApplicationUserManager userManager, IMapper mapper)
        {
            _userManager = userManager;
            _mapper = mapper;
        }

        public ActionResult Index()
        {
            var users = _userManager.Users.ToList();
            return View(_mapper.Map<IEnumerable<UserViewModel>>(users));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new UserCreateViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(UserCreateViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    PushWarning("Benutzer erstellen", "Bitte Eingaben überprüfen");
                    return View();
                }

                var entity = new ApplicationUser();
                _mapper.Map(model, entity);
                var result = await _userManager.CreateAsync(entity, model.Password);

                if (!result.Succeeded)
                {
                    PushError("Benutzer erstellen", "Fehler beim Erstellen des Benutzers");
                    return View();
                }

                PushSuccess("Benutzer erstellen", "Benutzer erfolgreich erstellt");
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                PushError("Benutzer erstellen", "Fehler beim Erstellen des Benutzers");
                _logger.Error(ex, "Error while creating user");
                return View();
            }
        }

        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            return View(_mapper.Map<UserCreateViewModel>(user));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, UserCreateViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }

                var entity = await _userManager.FindByIdAsync(id);
                _mapper.Map(model, entity);

                var result = await _userManager.UpdateAsync(entity);

                if (!result.Succeeded)
                {
                    return View();
                }

                result = await _userManager.RemovePasswordAsync(id);

                if (!result.Succeeded)
                {
                    return View();
                }

                result = await _userManager.AddPasswordAsync(id, model.Password);

                if (!result.Succeeded)
                {
                    return View();
                }

                PushSuccess("Benutzer bearbeiten", "Benutzer erfolgreich gespeichert");
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.Error(ex, $"Error while updating user {id}");
                return View();
            }
        }
    }
}

oiat.saferinternetbot.web/Views/Shared/_Header.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">SaferInternetBot</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        @if (User.Identity.IsAuthenticated)
        {
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Intent")">Kategorien</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("List", "DefaultAnswer")">Einstellungen</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "Bot")">Testen</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "User")">Benutzer</a>
            </li>
            <li>
                <a class="nav-link" href="@Url.Action("List", "Conversation")">Konversationen</a>
            </li>
        </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-danger" href="@Url.Action("Invalidate", "Cache", new { redirectUrl = Request.Url.PathAndQuery})">Cache leeren</a>
                </li>
            </ul>
            <span class="navbar-text">
                @User.Identity.Name
            </span>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Logout", "Login")">Ausloggen</a>
                </li>
            </ul>
        }
    </div>
</nav>

oiat.saferinternetbot.web/Views/Shared/_Headline.cshtml
<div class="row">
    <div class="col-12 mb-3 mt-4">
        <h1>@ViewBag.Title</h1>
    </div>
</div>

oiat.saferinternetbot.web/Views/Shared/_Layout.cshtml
@{
    Layout = null;
    Html.RequiresCssBundle("core");
    Html.RequiresJsBundle("core");
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Html.RenderCssHere()
    @RenderSection("Styles", required: false)
    <script type = 'text/javascript' >
        var appInsights=window.appInsights||function(config)
        {
            function r(config){ t[config] = function(){ var i = arguments; t.queue.push(function(){ t[config].apply(t, i)})} }
            var t = { config:config},u=document,e=window,o='script',s=u.createElement(o),i,f;for(s.src=config.url||'//az416426.vo.msecnd.net/scripts/a/ai.0.js',u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=['Event','Exception','Metric','PageView','Trace','Ajax'];i.length;)r('track'+i.pop());return r('setAuthenticatedUserContext'),r('clearAuthenticatedUserContext'),config.disableExceptionTracking||(i='onerror',r('_'+i),f=e[i],e[i]=function(config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o),s}),t
        }({
            instrumentationKey:'56512851-deb6-49bc-936e-2c7f673f005d'
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    @Html.Partial("_Header")
    <div class="container">
        @RenderBody()
    </div>
    @Html.RenderJsHere()
    @Html.Partial("_Notifications")
    @RenderSection("Scripts", required: false)
</body>
</html>

oiat.saferinternetbot.web/Views/Shared/_Notifications.cshtml
@using oiat.saferinternetbot.web.Helpers
@{
    var notifications = TempData["Notifications"];
}

@if (notifications != null)
{
    <script type="text/javascript">
        toastr.options.closeButton = true;
        toastr.options.progressBar = true;

        @foreach(var item in (List<Notification>) notifications)
            {
                <text>
        toastr.@(item.Type.ToString().ToLowerInvariant())('@item.Text', '@item.Title');
                </text>
            }

    </script>
}