oiat.saferinternetbot.web/Controllers/AnswerController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using mbit.common.logging;
using oiat.saferinternetbot.Business.Dtos;
using oiat.saferinternetbot.Business.Interfaces;
using oiat.saferinternetbot.web.Models;

namespace oiat.saferinternetbot.web.Controllers
{
    [Authorize]
    public class AnswerController : BaseController
    {
        private static readonly IMcLogger _logger = McLogFactory.GetCurrentLogger();

        private readonly IAnswerService _answerService;
        private readonly IIntentService _intentService;
        private readonly IMapper _mapper;

        public AnswerController(IAnswerService answerService, IMapper mapper, IIntentService intentService)
        {
            _answerService = answerService;
            _mapper = mapper;
            _intentService = intentService;
        }

        [HttpGet]
        public async Task<ActionResult> Index(Guid id)
        {
            var intent = await _intentService.GetById(id);
            var items = await _answerService.GetByIntentId(id);

            var model = new AnswerListViewModel
            {
                IntentId = intent.Id,
                IntentName = intent.Name,
                Items = _mapper.Map<IEnumerable<AnswerListItemViewModel>>(items)
            };

            return View(model);
        }

        [HttpGet]
        public ActionResult Create(Guid id)
        {
            return View(new AnswerEditViewModel { IntentId = id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Guid id, AnswerEditViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    PushWarning("Antwort erstellen", "Bitte Eingaben überprüfen");
                    return View();
                }

                var dto = new AnswerDto
                {
                    IntentId = id,
                    Text = model.Text
                };
                await _answerService.Add(dto);

                PushSuccess("Antwort erstellen", "Antwort erfolgreich erstellt");
                return RedirectToAction("Index", new { id = id });
            }
            catch (Exception ex)
            {
                PushError("Antwort erstellen", "Fehler beim Erstellen der Antwort");
                _logger.Error(ex, "Error while creating answer");
                return View();
            }
        }

        [HttpGet]
        public async Task<ActionResult> Edit(Guid id)
        {
            var answer = await _answerService.GetById(id);
            return View(_mapper.Map<AnswerEditViewModel>(answer));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Guid id, AnswerEditViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    PushWarning("Antwort bearbeiten", "Bitte Eingaben überprüfen");
                    return View();
                }

                var answer = await _answerService.GetById(id);
                answer.Text = model.Text;
                await _answerService.Update(id, answer);

                PushSuccess("Antwort bearbeiten", "Antwort erfolgreich gespeichert");
                return RedirectToAction("Index", new { id = model.IntentId });
            }
            catch (Exception ex)
            {
                PushError("Antwort bearbeiten", "Fehler beim Speichern der Antwort");
                _logger.Error(ex, $"Error while updating answer {id}");
                return View();
            }
        }

        [HttpGet]
        public async Task<ActionResult> Delete(Guid id)
        {
            var answer = await _answerService.GetById(id);
            await _answerService.Delete(id);
            PushSuccess("Antwort löschen", "Antwort erfolgreich gelöscht");
            return RedirectToAction("Index", new { id = answer.IntentId });
        }
    }
}

oiat.saferinternetbot.web/Controllers/IntentController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using oiat.saferinternetbot.Business.Interfaces;
using oiat.saferinternetbot.web.Models;

namespace oiat.saferinternetbot.web.Controllers
{
    [Authorize]
    public class IntentController : BaseController
    {
        private readonly IIntentService _intentService;
        private readonly IMapper _mapper;

        public IntentController(IIntentService intentService, IMapper mapper)
        {
            _intentService = intentService;
            _mapper = mapper;
        }

        public async Task<ActionResult> Index()
        {
            var items = await _intentService.GetAll();
            return View(_mapper.Map<IEnumerable<IntentViewModel>>(items));
        }
    }
}

oiat.saferinternetbot.web/Views/Answer/Create.cshtml
@model oiat.saferinternetbot.web.Models.AnswerEditViewModel
@{
    ViewBag.Title = "Neue Antwort";
}
@Html.Partial("_Headline")
<div class="row">
    <div class="col-12">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.IntentId)
            <div class="form-group">
                @Html.LabelFor(model => model.Text)
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            @Html.ActionLink("Zurück", "Index", "Answer", new { id = Model.IntentId }, new { @class = "btn btn-secondary" })
            <button type="submit" class="btn btn-primary">Erstellen</button>
        }
    </div>
</div>

oiat.saferinternetbot.web/Views/Answer/Edit.cshtml
@model oiat.saferinternetbot.web.Models.AnswerEditViewModel
@{
    ViewBag.Title = "Antwort bearbeiten";
}

@Html.Partial("_Headline")
<div class="row">
    <div class="col-12">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.IntentId)
            <div class="form-group">
                @Html.LabelFor(model => model.Text)
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            @Html.ActionLink("Zurück", "Index", "Answer", new { id = Model.IntentId }, new { @class = "btn btn-secondary" })
            <button type="submit" class="btn btn-primary">Speichern</button>
        }
    </div>
</div>

oiat.saferinternetbot.web/Views/Answer/Index.cshtml
@model oiat.saferinternetbot.web.Models.AnswerListViewModel
@{
    ViewBag.Title = "Antworten für " + Model.IntentName;
}
<div class="row">
    <div class="col-12">
        @Html.ActionLink("Zurück zu den Kategorien", "Index", "Intent")
    </div>
</div>
@Html.Partial("_Headline")
<div class="row mb-3">
    <div class="col-12">
        @Html.ActionLink("Neue Antwort erstellen", "Create", new { id = Model.IntentId }, new { @class = "btn btn-success btn-sm" })
    </div>
</div>
<div class="row">
    <div class="col-12">
        @Html.Partial("_List", Model.Items)
    </div>
</div>

oiat.saferinternetbot.web/Views/Answer/_List.cshtml
@model IEnumerable<oiat.saferinternetbot.web.Models.AnswerListItemViewModel>
@if (Model.Any()) { 
    <table class="table table-striped">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TextTruncated)
            </th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TextTruncated)
                </td>
                <td class="text-right">
                    @Html.ActionLink("Bearbeiten", "Edit", new { id = item.Id }, new { @class = "btn btn-warning btn-sm" })
                    @Html.ActionLink("Löschen", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-sm" })
                </td>
            </tr>
        }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-info">Es wurden noch keine Antworten erstellt.</div>
}