oiat.saferinternetbot.web/Controllers/ConversationController.cs
using AutoMapper;
using CsvHelper;
using CsvHelper.Configuration;
using mbit.common.logging;
using oiat.saferinternetbot.Business.Interfaces;
using oiat.saferinternetbot.web.Controllers;
using oiat.saferinternetbot.Web.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace oiat.saferinternetbot.Web.Controllers
{
    [Authorize]
    public class ConversationController : BaseController
    {
        private static readonly IMcLogger _logger = McLogFactory.GetCurrentLogger();

        private readonly IConversationService _conversationService;
        private readonly IMapper _mapper;

        public ConversationController(IConversationService conversationService, IMapper mapper)
        {
            _conversationService = conversationService;
            _mapper = mapper;
        }

        // GET: Conversation
        public async Task<ActionResult> List()
        {
            var data = await _conversationService.GetAllConversationIds();
            return View(data.Select(x => new ConversationOverviewViewModel() { ConversationId = x.conversationId, MessageCount = x.msgCount, LatestTimestamp = x.latestTimestamp }));
        }

        public async Task<ActionResult> Export(string id)
        {
            var decodedID = Encoding.UTF8.GetString(HttpServerUtility.UrlTokenDecode(id));
            var data = await _conversationService.GetConversation(decodedID);

            var records = data.Select(x => new ConversationMessageExportModel
            {
                Content = x.Content,
                Timestamp = x.Timestamp.ToString("dd.MM.yyy HH:mm:ss"),
                Type = x.Channel.ToString()
            }).ToList();

            using (var ms = new MemoryStream())
            {
                using (var writer = new StreamWriter(ms, Encoding.UTF8))
                {                    
                    using (var csv = new CsvWriter(writer, CultureInfo.InvariantCulture))
                    {
                        csv.Configuration.Delimiter = ";";
                        csv.Configuration.NewLine = NewLine.Environment;
                        csv.Configuration.ShouldQuote = (field, context) => true;

                        await csv.WriteRecordsAsync(records);
                        await csv.FlushAsync();
                    }
                }
                return File(ms.ToArray(), "text/csv", $"Konversation_{id}.csv");
            }
        }

        public async Task<ActionResult> Messages(string id)
        {
            var decodedID = Encoding.UTF8.GetString(HttpServerUtility.UrlTokenDecode(id));

            var data = await _conversationService.GetConversation(decodedID);
            var model = new ConversationDetailViewModel()
            {
                ConversationId = decodedID,
                MessageCount = data.Count,
                Messages = data.Select(x => _mapper.Map<ConversationMessageViewModel>(x))
            };
            return View(model);
        }

        public async Task<ActionResult> Delete(string id)
        {
            var decodedID = id ?? "NULL"; 
            try
            {
                decodedID = Encoding.UTF8.GetString(HttpServerUtility.UrlTokenDecode(id));
                await _conversationService.DeleteConversation(decodedID);
                PushSuccess("Konversation löschen", "Konversation wurde erfolgreich gelöscht");
            }
            catch (Exception ex)
            {
                PushError("Konversation löschen", "Es ist ein Fehler beim löschen der Konversation aufgetreten!");
                _logger.Error(ex, $"Error while deleting conversation \"{decodedID}\"");
            }
            return RedirectToAction(nameof(List));
        }
    }
}

oiat.saferinternetbot.web/Controllers/MessagesController.cs
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using Microsoft.Bot.Builder.Dialogs;
using Microsoft.Bot.Connector;
using oiat.saferinternetbot.web.Dialogs;

namespace oiat.saferinternetbot.web.Controllers
{
    [BotAuthentication]
    public class MessagesController : ApiController
    {
        /// <summary>
        /// POST: api/Messages
        /// Receive a message from a user and reply to it
        /// </summary>
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.GetActivityType() == ActivityTypes.Message)
            {
                await Conversation.SendAsync(activity, () => new RootDialog());
            }
            else
            {
                HandleSystemMessage(activity);
            }
            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }

        private Activity HandleSystemMessage(Activity message)
        {
            string messageType = message.GetActivityType();
            if (messageType == ActivityTypes.DeleteUserData)
            {
                // Implement user deletion here
                // If we handle user deletion, return a real message
            }
            else if (messageType == ActivityTypes.ConversationUpdate)
            {
                // Handle conversation state changes, like members being added and removed
                // Use Activity.MembersAdded and Activity.MembersRemoved and Activity.Action for info
                // Not available in all channels 
            }
            else if (messageType == ActivityTypes.ContactRelationUpdate)
            {
                // Handle add/remove from contact lists
                // Activity.From + Activity.Action represent what happened
            }
            else if (messageType == ActivityTypes.Typing)
            {
                // Handle knowing that the user is typing
            }

            return null;
        }
    }
}

oiat.saferinternetbot.web/Views/Conversation/List.cshtml
@using System.Text
@model IEnumerable<oiat.saferinternetbot.Web.Models.ConversationOverviewViewModel>
@{
    ViewBag.Title = "Konversationen";
}
@Html.Partial("_Headline")
<div class="row">
    <div class="col-12">
        <table id="conversations" class="table table-striped">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.ConversationId)</th>
                    <th>@Html.DisplayNameFor(model => model.MessageCount)</th>
                    <th>@Html.DisplayNameFor(model => model.LatestTimestamp)</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.ConversationId)</td>
                        <td>@Html.DisplayFor(modelItem => item.MessageCount)</td>
                        <td data-sort="@item.LatestTimestamp.ToString("yyyyMMddHHmmssfff")">@Html.DisplayFor(modelItem => item.LatestTimestamp)</td>
                        <td class="text-right">
                            @Html.ActionLink("Nachrichten", "Messages", "Conversation", new { id = HttpServerUtility.UrlTokenEncode(Encoding.UTF8.GetBytes(item.ConversationId)) }, new { @class = "btn btn-info btn-sm" })
                            @Html.ActionLink("Download", "Export", "Conversation", new { id = HttpServerUtility.UrlTokenEncode(Encoding.UTF8.GetBytes(item.ConversationId)) }, new { @class = "btn btn-warning btn-sm" })
                            <a href="#" class="btn btn-danger btn-sm" data-href="@Url.Action("Delete", "Conversation", new { id = HttpServerUtility.UrlTokenEncode(Encoding.UTF8.GetBytes(item.ConversationId)) })" data-toggle="modal" data-target="#confirm-delete">Löschen</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Konversation Löschen
            </div>
            <div class="modal-body">
                Sind sie sicher das sie die Konversation und alle Nachrichten löschen wollen ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
                <a class="btn btn-danger btn-ok">Löschen</a>
            </div>
        </div>
    </div>
</div>

@section Styles
{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.22/datatables.min.css" />
}

@section Scripts{
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.22/datatables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var table = $('#conversations').DataTable(
                {
                    "order": [[2, "desc"]],
                    "language": {
                        "lengthMenu": "_MENU_ Einträge pro Seite",
                        "zeroRecords": "Keine Einträge gefunden",
                        "info": "Seite _PAGE_ von _PAGES_",
                        "infoEmpty": "Keine Einträge gefunden",
                        "infoFiltered": "(gefiltert von _MAX_ Einträgen)",
                        "search": "Suche:",
                        "paginate": {
                            "first": "Erste",
                            "last": "Letzte",
                            "next": ">",
                            "previous": "<"
                        },
                    },
                    "stateSave": true
                });

            $('#confirm-delete').on('show.bs.modal', function (e) {
                $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
            });
        });
    </script>
}

oiat.saferinternetbot.web/Views/Conversation/Messages.cshtml
@using oiat.saferinternetbot.Web.Models
@model ConversationDetailViewModel
@{
    ViewBag.Title = "Nachrichten";
}
@Html.Partial("_Headline")
<div class="row">
    <div class="col-12">
        <div class="pb-4">
            <h4>Empfänger: @Html.DisplayFor(model => model.ConversationId)</h4>
            <h4>Anzahl der Nachrichten: @Html.DisplayFor(model => model.MessageCount) </h4>
        </div>
        <div class="pb-4">
            <table id="messages" class="table table-striped">
                <thead>
                    <tr>
                        <th>@Html.DisplayName(nameof(ConversationMessageViewModel.Timestamp))</th>
                        <th>@Html.DisplayName(nameof(ConversationMessageViewModel.Type))</th>
                        <th>@Html.DisplayName(nameof(ConversationMessageViewModel.Content))</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Messages)
                    {
                        <tr>
                            <td data-sort="@item.Timestamp.ToString("yyyyMMddHHmmssfff")">@Html.DisplayFor(modelItem => item.Timestamp)</td>
                            <td>@Html.DisplayFor(modelItem => item.Type)</td>
                            <td>@Html.DisplayFor(modelItem => item.Content)</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Styles
{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.22/datatables.min.css" />
}

@section Scripts{
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.22/datatables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#messages').DataTable(
                {
                    "order": [[0, "desc"]],
                    "language": {
                        "lengthMenu": "_MENU_ Einträge pro Seite",
                        "zeroRecords": "Keine Einträge gefunden",
                        "info": "Seite _PAGE_ von _PAGES_",
                        "infoEmpty": "Keine Einträge gefunden",
                        "infoFiltered": "(gefiltert von _MAX_ Einträgen)",
                        "search": "Suche:",
                        "paginate": {
                            "first": "Erste",
                            "last": "Letzte",
                            "next": ">",
                            "previous": "<"
                        },
                    },
                    "stateSave": true
                });
        });
    </script>
}